// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whbfupiowfgwzonalogw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoYmZ1cGlvd2Znd3pvbmFsb2d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDM1MDAsImV4cCI6MjA2NDM3OTUwMH0.euwihCUGff0ZgLR2IM2b4ETgm5f2VmAag6FWvAoEtMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);